In [1]:
import torch
import matplotlib.pyplot as plt
from torchmetrics import JaccardIndex


/home/dqian/miniconda3/envs/NYU-DL/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/dqian/miniconda3/envs/NYU-DL/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


In [3]:
# Load our own modules
import sys

sys.path.append("../src")

from data import ValidationDataset

In [8]:
dataset = ValidationDataset("../Dataset_Student")
val_dataloader = torch.utils.data.DataLoader(dataset, batch_size=5, num_workers=2)


In [9]:
model = torch.load("../simsiamgsta.pth", map_location=torch.device('cpu'))

In [29]:
# Look at SSL trained model
import random
sim = torch.nn.CosineSimilarity()


(x1, y1), (x2, y2) = random.choices(dataset, k=2)

x1 = x1.transpose(0, 1).unsqueeze(0)
x2 = x2.transpose(0, 1).unsqueeze(0)

x1, y1 = x1[:,:,:11], x1[:,:,11:]
x2, y2 = x2[:,:,:11], x2[:,:,11:]

print(x1.shape)
print(y1.shape)
print(x2.shape)
print(y2.shape)

torch.Size([1, 3, 11, 256, 256])
torch.Size([1, 3, 11, 256, 256])
torch.Size([1, 3, 11, 256, 256])
torch.Size([1, 3, 11, 256, 256])


In [30]:
model.eval()
with torch.no_grad():
    p1, p2, h1, h2 = model(x1, y1)
    
    q1, q2, k1, k2 = model(x2, y2)    

In [32]:
import torch.nn.functional as F

print(F.cosine_similarity(p1, h2))
print(F.cosine_similarity(p2, h1))

print(F.cosine_similarity(h1, h2))
print(F.cosine_similarity(p1, p2))

print(F.cosine_similarity(p1, q1))
print(F.cosine_similarity(h1, k1))


tensor([0.8144])
tensor([0.8034])
tensor([0.9539])
tensor([0.9906])
tensor([0.9712])
tensor([0.8079])
