In [44]:
import torch
import matplotlib.pyplot as plt
from torchmetrics import JaccardIndex


In [51]:
# Load our own modules
import sys

sys.path.append("./src")

from data import ValidationDataset

In [52]:
dataset = ValidationDataset("Dataset_Student")
val_dataloader = torch.utils.data.DataLoader(dataset, batch_size=5, num_workers=2)


In [53]:
model = torch.load("testseg.pkl", map_location=torch.device('cpu'))

In [54]:
# Look at SSL trained model
import random
sim = torch.nn.CosineSimilarity()


(x1, y1), (x2, y2) = random.choices(dataset, k=2)

x1 = x1.transpose(0, 1).unsqueeze(0)
x2 = x2.transpose(0, 1).unsqueeze(0)

x1, z1 = x1[:,:,:11], x1[:,:,11:]
x2, z2 = x2[:,:,:11], x2[:,:,11:]

print(x1.shape)
print(z1.shape)
print(x2.shape)
print(z2.shape)

torch.Size([1, 3, 11, 160, 240])
torch.Size([1, 3, 11, 160, 240])
torch.Size([1, 3, 11, 160, 240])
torch.Size([1, 3, 11, 160, 240])


In [55]:
model.eval()
with torch.no_grad():

    hx1 = model.encoder(x1)
    hx2 = model.encoder(x2)
    
    hz1 = model.encoder(z1)
    hz2 = model.encoder(z2)
    
    hpz1 = model.predictor(hx1)
    hpz2 = model.predictor(hx2)

In [56]:
import torch.nn.functional as F


print(hpz1.shape)
print(hz1.shape)
print(F.cosine_similarity(hx1, hx2))
print(F.cosine_similarity(hx1, hz1))

print(F.cosine_similarity(hpz1, hz1))


torch.Size([1, 1000])
torch.Size([1, 1000])
tensor([0.9087])
tensor([0.9468])
tensor([0.9061])
